name: Build, Test, Package and Publish GitHub release

on:
  workflow_dispatch:
    inputs:
      generate_build_artifact:
        description: "Build, test, verify and publish build artifact"
        type: boolean
        required: true
        default: false
      sha:
        description: "The last commit sha in the release"
        required: true
      version_number:
        description: "The release version number (i.e. 1.0.0b1)"
        required: true
      changelog_path:
        description: "Path to changes log"
        type: string
        default: "./CHANGELOG.md"
        required: false
      dry_run:
        description: "Launch test run"
        type: boolean
        default: true
        required: false

jobs:
  build-test-verify-publish-package:
    if: inputs.generate_build_artifact
    uses: dbt-labs/dbt-core-release-test/.github/workflows/build-verify-publish-package.yml@users/alexander-smolyakov/add-publish-github-release-stage
    with:
      sha: ${{ inputs.sha }}
      version_number: ${{ inputs.version_number }}

  publish-github-release:
    if: ${{ always() && !cancelled() }}
    needs: [build-test-verify-publish-package]
    uses: dbt-labs/dbt-release/.github/workflows/_github-release.yml@users/alexander-smolyakov/fix-github-release-workflow
    with:
      sha: ${{ inputs.sha }}
      version_number: ${{ inputs.version_number }}
      changelog_path: ${{ inputs.changelog_path }}
      testing: ${{ inputs.dry_run }}
